<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
        'key' => 'group_63a34123e2711',
        'title' => 'Ajustes Generales',
        'fields' => array(
            array(
                'key' => 'field_63a488946e3ba',
                'label' => 'Modulos de Bigcom',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_63a488c86e3bb',
                'label' => 'Configuracion de WhatsApp',
                'name' => '_check__whatsapp',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Completado',
                'ui_off_text' => 'No Completado',
            ),
            array(
                'key' => 'field_63a489476e3bc',
                'label' => 'Configuración de Merchant ID',
                'name' => '_check__merchant_id',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Completado',
                'ui_off_text' => 'No Completado',
            ),
            array(
                'key' => 'field_63a489eb6e3bd',
                'label' => 'Configuración de Carrito',
                'name' => '_check__configuracion_carrito',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Completado',
                'ui_off_text' => 'No Completado',
            ),
            array(
                'key' => 'field_63a48a276e3be',
                'label' => 'Formulario de Checkout',
                'name' => '_check__checkout_form',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Completado',
                'ui_off_text' => 'No Completado',
            ),
            array(
                'key' => 'field_63a48a4f6e3c0',
                'label' => 'Comprobante de Pago',
                'name' => '_check__flies_upload',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Completado',
                'ui_off_text' => 'No Completado',
            ),
            array(
                'key' => 'field_63a48a736e3c2',
                'label' => 'Transferencia Bancaria',
                'name' => '_check__bac_duplicator',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Completado',
                'ui_off_text' => 'No Completado',
            ),
            array(
                'key' => 'field_63a48a736e3c1',
                'label' => 'Configuracion de Emails',
                'name' => '_check__email_config',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Completado',
                'ui_off_text' => 'No Completado',
            ),
            array(
                'key' => 'field_63a48acb6e3c4',
                'label' => 'Configuración de Pedidos',
                'name' => '_check__orders_config',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Completado',
                'ui_off_text' => 'No Completado',
            ),
            array(
                'key' => 'field_63a48aeb6e3c6',
                'label' => 'Personalizar txt Botones',
                'name' => '_check__personalizador',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Completado',
                'ui_off_text' => 'No Completado',
            ),
            array(
                'key' => 'field_63a48bd96e3c7',
                'label' => 'Configuración de Direccines',
                'name' => '_check__setting_shipping',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Completado',
                'ui_off_text' => 'No Completado',
            ),
            array(
                'key' => 'field_63a34161e6044',
                'label' => 'Envios',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_63a341a6b3c77',
                'label' => 'Costo de Envio',
                'name' => 'shipping_cost_field',
                'type' => 'number',
                'instructions' => 'Agregue el valor que determinara el costo de envio en pesos mexicanos, tome en consideracion que este es el cobro que se hace por cada 5 kilos de peso en masa o peso volumetrico.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 99,
                'placeholder' => '',
                'prepend' => 'Mx',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
            array(
                'key' => 'field_63a34316b3c78',
                'label' => 'Peso Maximo Permitido',
                'name' => '_max_wehight',
                'type' => 'number',
                'instructions' => 'Establezca un peso maximo permitido por cada pedido segun la paqueteria que este ocupando',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 100,
                'placeholder' => '',
                'prepend' => 'Kg',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
            array(
                'key' => 'field_63a3439bb3c79',
                'label' => 'Mensaje a mostrar cuando un pedido ocupe el peso maximo',
                'name' => '__message_max_wehight',
                'type' => 'textarea',
                'instructions' => 'Escriba un mensaje que le sera mostrado al usuario cuando este exceda el peso maximo permitido por la paqueteria que esta ocupando.
    
    Este Campo Recibe 3 parametros en el siguiente Orden.
    
    %d = Peso total del carrito
    %d = Peso Maximo Permitido
    %s = Metodo deEnvio Publicado
    
    Tome en consideracion al momento de redactar su mensaje asi como se muestra en el mensaje por defecto.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 'Disculpe, usted tiene en su carrito %d kg y excede la cantidad maxima de %d kg para %s lamentamos informarle que nuestra paqueteria no podra hacer un solo envio por lo que sugerimos que haga varios pedidos sin exceder el limite permitido.',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'new_lines' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'bigcom-general-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 1,
    ));
    
    endif;		