<?php
if ( ! defined( 'WPINC' ) ) {
	die;
}

// Settings Page: WhatsApp

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_B8agE18aJtFCUpeIXyK8',
		'title' => 'Ajusta Los mensajes de WhatsApp a Tu Necesidad',
		'fields' => array(
			array(
				'key' => 'field_2mW2j08JWvJJCDNmORCb',
				'label' => 'Código de Área',
				'name' => 'codigo_de_area',
				'prepend' => '+',
				'type' => 'number',
				'instructions' => 'POR FAVOR INTRUDUZCA SU CODIGO DE AREA SEGUN EL PAIS QUE PERTENEZCA SOLO NUMEROS COMO SE INDICA EN EL EJEMPLO, POR DEFAULT ES 52 CODIGO DE AREA DE MEXICO',
				'required' => 0,
				'placeholder' => '52',
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 52,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_QG56w8LlQHfNaopZeNi9',
				'label' => 'Mensaje Global',
				'name' => 'msj_global',
				'type' => 'textarea',
				'instructions' => 'POR FAVOR ESCRIBE UN MENSAJE DE WHATSAPP PARA ENVIAR DE FORMA GLOBAL DESDE LAS ACCIONES DEL PEDIDO',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => '',
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_9Yi6HM2DZxVYyIGfeXyV',
				'label' => 'Validando Pago',
				'name' => 'msj_validando_pago',
				'type' => 'textarea',
				'instructions' => 'POR FAVOR ESCRIBE UN MENSAJE DE WHATSAPP PARA ENVIAR CUANDO SE ESTE VALIDANDO EL PAGO',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => '',
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_v4P044VWk8vpfa4XYPDQ',
				'label' => 'Pedido Enviado',
				'name' => 'msj_pedido_enviado',
				'type' => 'textarea',
				'instructions' => 'POR FAVOR ESCRIBE UN MENSAJE DE WHATSAPP PARA ENVIAR CUANDO EL PEDIDO ESTE ENVIADO',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => '',
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_O9x35eG8Q9Sn7hYY4teK',
				'label' => 'Pedido Fallido',
				'name' => 'msj_pedido_fallido',
				'type' => 'textarea',
				'instructions' => 'POR FAVOR ESCRIBE UN MENSAJE DE WHATSAPP PARA ENVIAR CUANDO EL PEDIDO FALLE',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => '',
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_3r2Jz64UiYRgobEnozZW',
				'label' => 'Procesando Pedido',
				'name' => 'msj_procesando_pedido',
				'type' => 'textarea',
				'instructions' => 'POR FAVOR ESCRIBE UN MENSAJE DE WHATSAPP PARA ENVIAR CUANDO SE ESTE PROCESANDO EL PEDIDO',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => '',
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_0C85mdkD8HS6sXeHL1uX',
				'label' => 'Pedido Cancelado',
				'name' => 'msj_pedido_cancelado',
				'type' => 'textarea',
				'instructions' => 'POR FAVOR ESCRIBE UN MENSAJE DE WHATSAPP PARA ENVIAR CUANDO SI ELPROCESO DE COMPRA SE CANCELA',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => '',
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_0C85mdkD8HS6sXeHL85X',
				'label' => 'Pedido Completado',
				'name' => 'msj_pedido_completado',
				'type' => 'textarea',
				'instructions' => 'POR FAVOR ESCRIBE UN MENSAJE DE WHATSAPP PARA ENVIAR CUANDO EL PROCESO DE COMPRA ESTE COMPLETO',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => '',
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'option-menu-whatsApp',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

endif;